language: generic
sudo: false
dist: jammy

env:
    global:
    - BYOND_MAJOR="516"
    - BYOND_MINOR="1687"
    - DM_BUILDFILE="IS12Warfare.dme"
    - SPACEMAN_DMM_VERSION=suite-1.4

matrix:
  include:
    - name: "Compile"
      addons:
        apt:
          packages:
            - libc6-i386
            - lib32gcc-s1
            - lib32stdc++6
      cache:
        directories:
            - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - chmod +x ./install-byond.sh
        - ./install-byond.sh
      script:
        - (! grep -rn 'step_[xy]' maps)
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash scripts/dm.sh ${DM_BUILDFILE}
